version : "3.8"
services:
  db:
    image: mysql
    container_name: db_kotopo
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: myadmin_kotopo
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST : db
    networks:
      - dev

  app:
    build: php
    container_name: app_kotopo
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev


networks:
  dev:

volumes:
  db-data:
