version: "3.9"

networks:
  traefik_bridge:
    name: traefik_bridge

services:
  php:
    container_name: php
    build:
      context: ./docker/php-apache
      target: php
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - BASE_URL=http://${DOMAIN}
      - DATABASE_URL=mysql://root:root@db:3306/kotopo?serverVersion=mariadb-10.8.3
      - MAILER_DSN=smtp://mailer:1025
      - MAIL_CONTACT_FROM=contact@kotopo.localhost
      - MAIL_CONTACT_TO=hello@kotopo.localhost
    volumes:
      - ./app:/var/www/kotopo
      - ./docker/php-apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - traefik_bridge
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik_bridge
      traefik.http.routers.kotopo.entrypoints: web
      traefik.http.routers.kotopo.rule: Host(`${DOMAIN}`)