version: '3.8'


networks:
  app_bridge:
    name: app_bridge

volumes:
  db_data:

services:
  database:
    image: mariadb:latest
    container_name: mariaDB
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app_bridge

  php:
    container_name: php
    build:
      context: ./docker/
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/kotopo
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - database
    networks:
      - app_bridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8083:80'
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app_bridge

