version: "3.9"

networks:
  mariadb_bridge:
    name: mariadb_bridge
  traefik_bridge:
    name: traefik_bridge
  mailhog_bridge:
     name: mailhog_bridge

volumes:
  db_data:

services:
  php:
    container_name: php
    build:
      context: ./docker/php-apache
      target: php
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
      - BASE_URL=http://${DOMAIN}
      - DATABASE_URL=mysql://root:root@db:3306/kotopo?serverVersion=mariadb-10.8.3
      - MAILER_DSN=smtp://mailer:1025
      - MAIL_CONTACT_FROM=contact@kotopo.localhost
      - MAIL_CONTACT_TO=hello@kotopo.localhost
