# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        environment:
          IMAGE_NAME: lechilddd/symfony-docker
    steps:
      - checkout # Étape 1
      - setup_remote_docker

      - run: # Étapes 2 & 3
          name: "Build and push Docker image"
          command: |
            IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
            APP_VERSION="${IMAGE_TAG}"
            GIT_COMMIT="${CIRCLE_SHA1:0:7}"
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} --build-arg APP_VERSION=${APP_VERSION} --build-arg GIT_COMMIT=${GIT_COMMIT} .
            
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
            fi
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker push ${IMAGE_NAME}
  deploy: # Étape 4
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "51:2c:bf:10:3d:c0:16:08:6f:23:ae:79:8e:cb:82:9b"
      - run:
          name: "Deploy image to production"
          command: |
            ssh root@${PROD_SERV_IP} "cd ${PROD_PATH} && ./deploy.sh"

# On éxécute ces étapes lors d'un commit sur la branche master uniquement
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
