# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
        environment:
          IMAGE_NAME: lechilddd/symfony-docker
    steps:
      - checkout # Étape 1
      - setup_remote_docker

      - run: # Étapes 2 & 3
          name: "Build and push Docker image"
          command: |
            IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
            APP_VERSION="${IMAGE_TAG}"
            GIT_COMMIT="${CIRCLE_SHA1:0:7}"
            docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
            
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
                docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
            fi
            echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
            docker push ${IMAGE_NAME}
  deploy: # Étape 4
    machine:
      image: lechilddd/symfony-docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "49:56:69:de:69:12:38:c4:71:36:82:37:0d:24:2c:be"
      - run:
          name: "Deploy image to production"
          command: |
            ssh root@${PRODUCTION_SERVER_IP} "cd ${PRODUCTION_SERVER_PATH} && .docker/prod/deploy.sh"

# On éxécute ces étapes lors d'un commit sur la branche master uniquement
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
