---
global:
  sendAnonymousUsage: false
  checkNewVersion: false
  #insecureSNI: false

api:
  insecure: true
  dashboard: true

log:
  format: common
  level: DEBUG

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    watch: true
    swarmMode: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      redirections:
        entryPoint:
          to: web
          scheme: http